### ISSUE TITLE
 threshold

### ISSUE THREAD

**Issue by cervineee** [LanglandsLin/ActCLR#12]
Hello, in which part of the code is the threshold you mentioned in your paper?
“The actionlet region is the area where the value of the generated actionlet Aitv exceeds a certain threshold, while the non-actionlet region is the remaining part.”

**Comment by cervineee** [comment]
second question：How do you initialize the process group for distributed training when you call the _batch_shuffle_ddp method in a batch shuffle?

**Comment by LanglandsLin** [comment]
Here is the threshold:
https://github.com/LanglandsLin/ActCLR/blob/23c62f5eff793bc5157da2ea6a22b6b4b7e5cd93/net/st_gcn.py#L95C1-L98C29

**Comment by cervineee** [comment]
Thank you very much for your answer❥
https://github.com/LanglandsLin/ActCLR/blob/23c62f5eff793bc5157da2ea6a22b6b4b7e5cd93/net/st_gcn.py#L99 Is the returned dimension NM, 1, T, V? If so, how is it transferred to m = self._generate_mask(x, N, M, mean_feat)
             pc, _ = self._mask_pool(x, m)
 The dimension of m in _mask_pool is required to be T V (bool) # paste True

**Comment by LanglandsLin** [comment]
The input of self._mask_pool() can be either (T V) or (NM 1 T V)

**Comment by cervineee** [comment]
Hello, when you are seeking mean_feat, do you operate online or offline? When using im_k, idx_k_unshuffle = self._batch_shuffle_ddp(im_k) to perform batch shuffling, what dimensions are averaged?

**Comment by cervineee** [comment]
https://github.com/LanglandsLin/ActCLR/blob/23c62f5eff793bc5157da2ea6a22b6b4b7e5cd93/net/st_gcn.py#L141
Hello, why set the value of Num class to 128

**Comment by LanglandsLin** [comment]
> https://github.com/LanglandsLin/ActCLR/blob/23c62f5eff793bc5157da2ea6a22b6b4b7e5cd93/net/actclr.py#L346
> 
> 
> Hello, can you tell me how the batch processing operation here is carried out? Is using batch_unshuffle_ddp for batch shuffling different samples passed into the GPU? How do you understand using Sample 1 to compare the shuffling of Sample 1 and Sample 2

This is an operation in moco in order to make the mean variance of the data on different gpu's not appear different.

**Comment by cervineee** [comment]
> 我们将大于 1 的区域视为一个动作，尽管对于小于 1 的区域，我们没有将其映射到 0，因此是一个软阈值。这是阈值：
> 
> https://github.com/LanglandsLin/ActCLR/blob/23c62f5eff793bc5157da2ea6a22b6b4b7e5cd93/net/st_gcn.py#L98C29
Hello, after using a soft threshold, input it into def_mask_pool for processing. The determined p, which is the relative motion feature, is determined by judging the areas in the mask that are greater than 1 or greater than 0
I'm very sorry to bother you, but I'm not clear about the concept of soft threshold. Could you please explain it in detail

**Comment by cervineee** [comment]
> 我们将大于 1 的区域视为一个动作，尽管对于小于 1 的区域，我们没有将其映射到 0，因此是一个软阈值。这是阈值：
> 
> https://github.com/LanglandsLin/ActCLR/blob/23c62f5eff793bc5157da2ea6a22b6b4b7e5cd93/net/st_gcn.py#L98C29

Hello, after using a soft threshold, input it into def_mask_pool for processing. The determined p, which is the relative motion feature, is determined by judging the areas in the mask that are greater than 1 or greater than 0
I'm very sorry to bother you, but I'm not clear about the concept of soft threshold. Could you please explain it in detail

**Comment by cervineee** [comment]
> 我们将大于 1 的区域视为一个动作，尽管对于小于 1 的区域，我们没有将其映射到 0，因此是一个软阈值。这是阈值：
> 
> https://github.com/LanglandsLin/ActCLR/blob/23c62f5eff793bc5157da2ea6a22b6b4b7e5cd93/net/st_gcn.py#L98C29

Hello, after using a soft threshold, input it into def_mask_pool for processing. The determined p, which is the relative motion feature, is determined by judging the areas in the mask that are greater than 1 or greater than 0？
I'm very sorry to bother you, but I'm not clear about the concept of soft threshold. Could you please explain it in detail
