### ISSUE TITLE
Why can't I get results as good as reported?

### ISSUE THREAD

**Issue by Moomin-Fin** [LanglandsLin/ActCLR#3]
Hello, I followed your instructions to further implement the training of ActCLR on the pre-trained weights provided by AimCLR. However, the linear evaluation results I obtained are very different from those reported (more than 2%) in joint, bone, motion and 3s. I would like to politely ask you about possible solutions. Did you not directly use the model released by AimCLR, but retrained it yourself?

**Comment by LanglandsLin** [comment]
Sorry for the confusion. We do retrain aimclr. We will check the code and release our training weights for reference.

**Comment by qinbaigao** [comment]
May I ask if this is due to the use of 64 frames in the linea evaluation.

**Comment by LanglandsLin** [comment]
I retrained it and found no drop in performance. So I don't know if you changed any parameters. It's worth noting that the batch size of the linear evaluation has a large impact on the results, we found that 1024 would be significantly better than a smaller batch size. whereas we tested with 50 fps, this point does make a small difference in the released code.
